#!/usr/bin/env bash
# This Script connects to the server 52.86.161.106  using the users private key
# stored in a file school Found in the users home directory

ssh -i ~/.ssh/school ubuntu@52.86.161.106
