#!/usr/bin/env bash
# This Script connects to the server 18.209.225.230  using the users private key
# stored in a file school Found in the users home directory

ssh -i ~/.ssh/school ubuntu@18.209.225.230
